### PR TITLE
Use JSON for control data instead of evil eval of remote content.

### PR DESCRIPTION
**Pull request by welwood08**
I may be paranoid about security, but I don't think it's wise to use eval at all, certainly not by default anyway.

This requires the control post to be changed to a JSON string, something like `{"speedThreshold":5000,"rainingRounds":250}`. This also happens to be valid no-op code if an outdated script continues to use eval.

### CODE REVIEW

**Comment by Eriner** [comment]
+1. Using eval is a terrible idea. It's never good to pull remote code the could be possibly modified (in transit or at source) and eval() it.

**Comment by wchill** [comment]
Good approach. I do realize the security risk eval imposes (hence the startup warning) but I will be keeping it in, just not enabled by default. (Probably will use another control post for it.)

Will merge for now.

**Comment by welwood08** [comment]
@wchill If the reason for keeping eval in some form is to allow script auto-update, I have an idea for that which avoids eval and can be triggered from the existing control post that this PR converted to JSON.

**Comment by wchill** [comment]
Send me a PR then when ready.

**Comment by welwood08** [comment]
See #145.

**Pull request merged**
