### PR TITLE
Added Treasure to autofire.

### PR DESCRIPTION
**Pull request by co-zz-deRitter**
Treasure is now bundled with Metal Detector. It fires if MD is not available. It otherwise follows the same logic.

### CODE REVIEW

**Comment by wchill** [comment]
Treasure should autofire automatically after cooldown during the first 30 rounds, then follow MD logic.

**Comment by co-zz-deRitter** [comment]
Done. Treasure autofires <= level 30 in addition to following MD.

**Comment by ozerugae** [comment]
@codeRitter 
Quick question, while this isn't merged: why does it trigger when `enemyBossHealthPercent >= 0.9` ? Shouldn't it be `enemyBossHealthPercent <= 0.20 && enemyBossHealthPercent > 0.1)`
As metal detector only increases the gold that is dropped on monster death not while it is alive.

Pretty much this: https://github.com/RockyTV/steamSummerMinigame/commit/35396efe3b6eebb127c7fc20ad9d5d031ba26cbc

**Comment by co-zz-deRitter** [comment]
I'm not entirely sure, but I think that the assumption is that bosses usually die within the 20 second duration. And it does seem that that usually is the case - most tend to die too quickly to wait for the 10-20% window.

That said, I'd be all for changing the MD trigger rules. I just wasn't doing that here.

**Comment by ozerugae** [comment]
Alright then; most of the time, for me at least, the boss lasts for a very long time.

**Pull request merged**
