### PR TITLE
Fix Cluster Bomb + Cripple Monster not working

### PR DESCRIPTION
**Pull request by 3xo**

### CODE REVIEW

**Comment by wchill** [comment]
This actually doesn't fix Cripple Monster.

**Comment by corymcdonough** [comment]
tryUsingItem() instead of triggerAbility() ? Is this a mistake that the code originally had it as an ability? Or is the game coded with Cripple Monster as a limited-use ability somehow?

**Comment by campbeb** [comment]
After 04436e14506881b58d6016b233dbe0743c1d7417, this PR should be reworked or closed.

**Comment by wchill** [comment]
Closing pending #175.

**Pull request closed without merging**
