### PR TITLE
Footer covering info box fix

### PR DESCRIPTION
**Pull request by ozerugae**
Basically add it before the footer_spacer div / after the game_options div. Not inside the game_options div

https://github.com/wchill/steamSummerMinigame/pull/155

### CODE REVIEW

**Comment by ozerugae** [comment]
Tested it. It is working, however does the 'Throttle game renderer' require a refresh?

**Comment by ozerugae** [comment]
Woah, wrong thing

**Comment by wchill** [comment]
Oh no you changed the version :(

**Comment by wchill** [comment]
Also, this breaks with the new lane info box I just added. Sorry

**Comment by ozerugae** [comment]
Have no idea how it happened, was using the online editor. I tried again here: https://github.com/wchill/steamSummerMinigame/pull/180

**Pull request closed without merging**
