### PR TITLE
Slowdown before n*100 level

### PR DESCRIPTION
**Pull request by veniversum**
Reduce clickrate after if level%100 > 90

### CODE REVIEW

**Comment by Ihysoal** [comment]
The way you currently have it, being inside the if (level % control.rainingRounds === 0) { } block, this will only execute during a boss level, making it effectively useless.

**Comment by MarkVabulas** [comment]
remove all requirements for it to depend on speed, we wnat to start at level 100, not 2000

**Comment by Ihysoal** [comment]
This was more a problem with speedThreshold not being set at 1 or something still.

**Comment by MarkVabulas** [comment]
veni, can it read %raininggold and +- the safety variable defined at the top....

if valve changes it to be more effective every 1000 rounds, id rather change a single variable than 100 magicnumbers throughout the code.

**Comment by veniversum** [comment]
Implemented above suggestions. Should we lower speedThreshold to something lower like 100?

**Pull request merged**
