### PR TITLE
Fix issue wchill/steamSummerMinigame#55

### PR DESCRIPTION
**Pull request by veniversum**

### CODE REVIEW

**Comment by wchill** [comment]
Can you change line 497 to

```
if (targetIsTreasure || targetIsBoss)
```

**Comment by ozerugae** [comment]
Just saw the issue and was fixing it :p, @veniversum you beat me.

@wchill 
might want to change it to 

``` javascript
if (!targetIsTreasure || !targetIsBoss)
```

Since you only want to switch to a gold rain lane when the target is NOT a treasure type or Boss type

**Comment by veniversum** [comment]
@wchill should be alright now

**Comment by wchill** [comment]
read @oedw's comment, I missed that too. Add the NOTs

**Comment by ozerugae** [comment]
@wchill @veniversum 

change it to

``` javascript
if (!targetIsTreasure && !targetIsBoss)
```

On the boss scene, !targetIsTreasure evaluates to true and will switch lanes still. Same with the case of treasure

Had it correct here: https://github.com/oedw/steamSummerMinigame/commit/d438f0f99b8ef7b3205bb9b1b0448946cb816520

**Pull request merged**
