### PR TITLE
Fix syntax errors introduced during ability unification

### PR DESCRIPTION
**Pull request by welwood08**
I'm an idiot sometimes. :)

### CODE REVIEW

**Comment by welwood08** [comment]
This alone doesn't seem to fix it, so there may indeed be a syntax error. It seems to die in an earlier loop before reaching my own obviously broken code.

**Comment by welwood08** [comment]
Since I can no longer reproduce, I suspect it's something to do with the waiting for players to join game start dialog. Looks like it's an undefined variable being used as an array/object. Anyway, this for PR as it is probably isn't needed - I see prototype has added an each method to the array prototype.

**Comment by welwood08** [comment]
I think I'm losing it.
`TypeError: BOSS_DISABLED_ABILITIES.each is not a function`

**Comment by welwood08** [comment]
FYI, this was my first attempt to rebase a branch in git. If there are no problems I'll attempt the same with #60 that's been getting more difficult to merge with upstream.

**Comment by wchill** [comment]
Can we get this tested?

**Comment by co-zz-deRitter** [comment]
Without looking up the documentation for either each or forEach (so I'm not sure why the change is needed), I can tell you that this seems to work (Chrome) visually. Plus:

Ran a test script in the console:
var BOSS_DISABLED_ABILITIES = ['MORALE_BOOSTER', 'GOOD_LUCK_CHARMS', 'TACTICAL_NUKE', 'CLUSTER_BOMB', 'NAPALM', 'CRIT', 'CRIPPLE_SPAWNER', 'CRIPPLE_MONSTER', 'MAX_ELEMENTAL_DAMAGE', 'REFLECT_DAMAGE','THROW_MONEY_AT_SCREEN'];
var test_each = [];
var test_forEach = [];
BOSS_DISABLED_ABILITIES.each(function(t){test_each.push(t);});
BOSS_DISABLED_ABILITIES.forEach(function(t){test_forEach.push(t);});
JSON.stringify(test_each)==JSON.stringify(test_forEach);

And got true, showing that at least 2 of the each/forEach changes work as expected.
Also tossed a console.log after the 3rd each/forEach, and the log displayed the same loot before and after implementing these changes.

Seems fine by me, at least in Chrome.

**Comment by welwood08** [comment]
[].each is not a standard EcmaScript feature, I believe it only happens to work because the prototype.js library is adding it. What I know for certain is that when combined with #60, .each fails with a TypeError every time.

**Comment by co-zz-deRitter** [comment]
Makes perfect sense.

forEach is, at least for me, performing exactly as expected. (Which means I give the pull a green light.)

**Comment by wchill** [comment]
Looks good.

**Pull request merged**
