### PR TITLE
Convert from JSHint to ESLint and enforce tab indentation

### PR DESCRIPTION
**Pull request by welwood08**
Implementation for wchill#184

### CODE REVIEW

**Comment by welwood08** [comment]
Rebased onto 1caabf9fc2b4662359682c65d370264e51f88cf5

**Comment by welwood08** [comment]
To resolve the conflicts while rebasing, I simply took 1caabf9fc2b4662359682c65d370264e51f88cf5 verbatim, replaced all groups of 4 spaces with tabs, indented everything inside the outer anonymous function by 1, deleted the blank line just before the end of that outer function, indented a block of 4 lines that had been using 2-space indentation, and tested with eslint.

GitHub is probably saying there's a merge conflict because of the blank line deletion. :/

**Comment by welwood08** [comment]
I'll take the opportunity to rebase again on the new head 69db50bd9cac5d683c209d4c1a4208dc4bbf5cfd, this time without deleting the blank line!

**Comment by wchill** [comment]
All right, I will wait

**Comment by welwood08** [comment]
Whoops, forgot to say it's done - green tick from travis is back as well. :)

**Pull request merged**
