### PR TITLE
Targets lane with Raining Gold ability active and auto use Morale Booster

### PR DESCRIPTION
**Pull request by ozerugae**

### CODE REVIEW

**Comment by ozerugae** [comment]
Incremented; the low creep targeting doesn't seem to work correctly now though, dunno how I broke it.

**Comment by ozerugae** [comment]
Nevermind, seems to move to a lane with a dying creep now.

**Comment by wchill** [comment]
Looks good, but gonna put it on hold for the moment as there's some additional logic changes I need to make elsewhere. Need to make sure they'll work with this.

**Comment by Gnaget** [comment]
I wrote something like this too, then I saw your request.  I think a combination of our approaches would be best.  Mine checked the stacks of raining gold and multiplied it by the monster's gold.  Then prioritized off that.  In case there are multiple lanes with raining gold at the same time

**Comment by Gnaget** [comment]
Relevant code: 

```
for (var i=0; i<3; i++) {
    if (g_Minigame.m_CurrentScene.m_rgLaneData[i].abilities[17]) {
        var stacks = g_Minigame.m_CurrentScene.m_rgLaneData[i].abilities[17];
            for(var e=0; e<g_Minigame.m_CurrentScene.m_rgEnemies.length; e++) {
                var enemyGold = g_Minigame.m_CurrentScene.m_rgEnemies[e].m_data.gold;
                    if (stacks * enemyGold > potential) {
                        potential = stacks * enemyGold;
                        potentialBaddie = g_Minigame.m_CurrentScene.m_rgEnemies[e];
                    }
            }
    }
}
```

```
```

**Comment by ozerugae** [comment]
@Gnaget good idea, will try to implement it

**Comment by ozerugae** [comment]
@Gnaget Implemented! Should work nicely :)

**Comment by ozerugae** [comment]
Nvm, Doesn't work. Don't implement it.

**Comment by ozerugae** [comment]
Will close until I fix

**Comment by ozerugae** [comment]
Let me know if there are any issues, will update to use g_Minigame.m_CurrentScene.m_rgLaneData[i].abilities[17] later on.

**Comment by wchill** [comment]
Wait, so is this ready to merge or no?

**Comment by ozerugae** [comment]
@wchill yeah, I'll change it again in a few moments though

**Comment by Gnaget** [comment]
Not sure if this is the issue, but I see that my if statement was wrong.  A typeof check should work.
    if (typeof g_Minigame.m_CurrentScene.m_rgLaneData[i].abilities[17] != 'undefined')

**Comment by ozerugae** [comment]
@Gnaget Seems to work now, gonna wait for a boss level to see if it REALLY works correctly ;)

**Comment by wchill** [comment]
Shouldn't take more than about 5 minutes

**Comment by ozerugae** [comment]
@wchill Done
@Gnaget Thank you, worked :)

**Pull request merged**
