### PR TITLE
update window title with gamelevel

### PR DESCRIPTION
**Pull request by cuteanon**

### CODE REVIEW

**Comment by ozerugae** [comment]
Tested, works fine. Also why not just use document? Many other parts of the code use document

**Comment by wchill** [comment]
Game level is already visible on the breadcrumb trail at the top of the page.

**Comment by cuteanon** [comment]
gamelevel not gameid ...

It shows the level progress in the task bar.

**Comment by wchill** [comment]
Ah, my bad.

Also, you shouldn't need to include document in the anonymous function, as @oedw stated. Can you please remove?

**Comment by wchill** [comment]
@blyzzz please rebase and I will merge.

**Pull request closed without merging**
