### PR TITLE
Added auto-buy logic for upgrades

### PR DESCRIPTION
**Pull request by makaRTH**
This was originally based off of russeli's code, but most of the core logic has changed.
Have yet to add ability purchases (if we want to use and don't have, then buy), and boss loot upgrades

### CODE REVIEW

**Comment by makaRTH** [comment]
Lol, took a couple tries to pass build, too used to Python

**Comment by ozerugae** [comment]
Is it ready for test?

**Comment by ozerugae** [comment]
Seemed to upgrade just fine so far: 
capture

will update once it upgrades bionic finger

No probable upgrades yet for the auto clicker:
capture2

**Comment by makaRTH** [comment]
Yeah, I've been running it for a few hours now, and so has a co-worker of mine, both with no issues. The only thing I've really noticed is that it can have a hard time upgrading the lower tier auto-attacks to open up the next tier sometimes, I may need to look ahead more than one tier of upgrades for it to value the auto-attack upgrades more. In reality though, the auto-attack is a very small portion of the overall dps if auto-click is enabled.

**Comment by MarkVabulas** [comment]
With the current WH strat trying to minimize DPS on raining gold levels, can we get you to modify this code to avoid ALL auto-dps damage except the first level (which lets it change lanes)?  The current idea is to take as long as possible on every raining gold level, so that we can put out something akin to 50,000 WH during the span of 1 boss....

**Comment by makaRTH** [comment]
@Trouvist Done. I commented out the auto-dps portion entirely. That way once the game is loaded the user only has to click the auto-fire once they're ready to start lane-changing stuffs.

**Comment by makaRTH** [comment]
Is this still in demand at all? I can resolve merge conflicts easily enough, and I was thinking of adding options to enable/disable autobuying, and potentially adding badge purchases as well, but if there is no demand then I'll spend the time on something else instead. Let me know

**Comment by ryantheleach** [comment]
People seem to be using a seperate auto buy script that is compatible with wchill. https://github.com/Pawsed/SteamMonsterAutoUpgradeManager/blob/master/upgrademanager.user.js

**Comment by makaRTH** [comment]
@ryantheleach Yeah, I've gathered that, and so I don't plan to work on this anymore. I do think it would be much more convenient to have the auto-buying included though rather than in a separate script.

**Pull request closed without merging**
