### PR TITLE
Script auto-updater controlled by version property in control JSON.

### PR DESCRIPTION
**Pull request by welwood08**
Currently the comparison between versions is a simple inequality, maybe in the future we want to implement a "greater than current" check.

Only update the version string in the control JSON after committing the same version into the script.

### CODE REVIEW

**Comment by wchill** [comment]
This does not work due to Content Security Policy.

**Comment by wchill** [comment]
```
> var updateURL = "https://raw.githubusercontent.com/wchill/steamSummerMinigame/master/autoPlay.user.js";
< undefined
> function updateCode() {
          $J.ajax({
              url: updateURL,
              dataType: "script"
          });
  }
< undefined
> updateCode()
< jquery-1.11.1.min.js?v=.isFTSRckeNhC:4 Refused to load the script 'https://raw.githubusercontent.com/wchill/steamSummerMinigame/master/autoPlay.user.js?_=1434374656866' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com http://steamapi-a.akamaihd.net/ https://steamapi-a.akamaihd.net/ http://ajax.googleapis.com https://ajax.googleapis.com".
```

**Comment by welwood08** [comment]
Ah sorry, thought I could take a shortcut. I'll use the old-fashioned method and update this branch.

**Comment by wchill** [comment]
If you plan on using XMLHttpRequest, it will give you the same error - I already tried. The only place where you can load code AFAIK is from Steam Community sites, but that means having to parse it which is an issue.

That's why I had everything in a forum post - it's accessible even with the CSP.

**Comment by welwood08** [comment]
No, I plan to insert a script node into the head of the HTML, I know that works fine for another of my userscripts that has used that method for years.

**Comment by wchill** [comment]
I think someone mentioned that the Steam page blocks injecting script tags, you're welcome to try though.

**Comment by welwood08** [comment]
You're right in that only a specific set of domains are allowed for script nodes, I had not encountered that security functionality before. Forget about this for now, I may have other ideas to get around eval later.

**Pull request closed without merging**
