### PR TITLE
Footer covering info box fix

### PR DESCRIPTION
**Pull request by ozerugae**
https://github.com/wchill/steamSummerMinigame/issues/136

Basically add it before the footer_spacer div / after the game_options div. Not inside the game_options div

### CODE REVIEW

**Comment by wchill** [comment]
I haven't decided spacing yet. Can you rebase?

**Comment by wchill** [comment]
Is this ready to merge?

**Comment by ozerugae** [comment]
I'm trying to squash it and am having issues. Mind if I close this and reopen a new one?:(

**Comment by wchill** [comment]
Sure

**Pull request closed without merging**
