### PR TITLE
Add commas to displayed numbers for readability

### PR DESCRIPTION
**Pull request by half-duplex**
[Result](https://i.imgur.com/IOPwNPJ.png)

### CODE REVIEW

**Comment by not4u2kno** [comment]
+1

**Comment by ryantheleach** [comment]
Please don't spam this in twitch.

**Comment by blole** [comment]
You might also be interested in this
https://github.com/blole/steamSummerMinigameNumberFormatter
it replaces e.g. 87,654K with 87.6M

**Comment by half-duplex** [comment]
Personally, I like having all the digits, except for maybe the skip count, but thanks for the link!

ryantheleach - one message, of interest to people there, about a nontrivial usability improvement... don't think that can be called spam.

**Pull request closed without merging**
