### PR TITLE
Wormholes spam ~3per second!

### PR DESCRIPTION
**Pull request by co-zz-deRitter**
Lowering the tickrate to 100ms gets us data very fast from the server. Using Timeouts, we attempt using Wormholes 10 times per second.

Yay!

I successfully used this right before the reset. It was awesome.

### CODE REVIEW

**Comment by co-zz-deRitter** [comment]
Grrr. This Travis bot.

**Comment by co-zz-deRitter** [comment]
Bah, yeah chat just let me know that the lower tickrate could DDoS the server. I'll poke around for a better solution. Sadly I have a dentist appointment momentarily.

**Comment by blole** [comment]
I experienced 3 per second to be the maximum. See my latest comment in #254.

**Comment by co-zz-deRitter** [comment]
Noted, I can do a touch of code changing to match that cap.

EDIT: Leaving now. The script seems to be working for me. I'd love more time to test it, but oh well. I'll be back. (The 1 time people didn't skip x00 boss, it used 13 in a few seconds.)

**Pull request closed without merging**
