### PR TITLE
autoBuyBadges: added autobuy logic. 10 whormoles for 1 like new, rest…

### PR DESCRIPTION
**Pull request by cadartichaut**
… to treasures

### CODE REVIEW

**Comment by cadartichaut** [comment]
Autobuys badges following the logic 10 wormholes for 1 Like New, then fills with treasures

**Comment by Ihysoal** [comment]
I like it, but you're buying at a 9:1 ratio.

(Also, I personally think you shouldn't remove the option to manually buy first. But let's see if Trouvist commits)

**Comment by cadartichaut** [comment]
Maybe add a button to the manual buy list to purchase the Badges automatically ?

**Comment by MayeulC** [comment]
That would be useful. Would you like some help ?

EDIT : did a draft here : https://github.com/MayeulC/steamSummerMinigame/commit/cd42b1e4de303f13d900bce543402ebba7cb5144

**Comment by cadartichaut** [comment]
Looks good, but I don't understand the %26. What I had was working fine, buying a Like New every 10 loop turn

Edit: nervermind, I thought 1:10 was optimized, apparently it's 1:25 now ?

**Pull request closed without merging**
