### PR TITLE
fixed items such as crit not triggering

### PR DESCRIPTION
**Pull request by adrianmace**

### CODE REVIEW

**Comment by co-zz-deRitter** [comment]
Thanks, I've been trying to do this for 20 minutes, but as it's my first time using GitHub, I had no idea what I was doing.

**Comment by wchill** [comment]
Verified working?

**Comment by co-zz-deRitter** [comment]
Yes. I've been using this fix for over 30 minutes.

**Comment by adrianmace** [comment]
personally, yep.

( Chrome Dev / OS X El Capitan )

**Comment by wchill** [comment]
Thanks a lot, merging.

**Comment by adrianmace** [comment]
No worries! Happy to help out :)

Looks like you bumped the version without merging first..

**Pull request merged**
