### PR TITLE
Don't refresh on boss

### PR DESCRIPTION
**Pull request by ozerugae**
Regarding: https://github.com/wchill/steamSummerMinigame/issues/104

Thanks @luanmuniz @meekmeekmeek

### CODE REVIEW

**Comment by luanmuniz** [comment]
Lets beat this game! \o/

**Comment by co-zz-deRitter** [comment]
Seems to work. I ran the following code in console:

// SETUP functions and vars for console
var ENEMY_TYPE = {
    "SPAWNER": 0,
    "CREEP": 1,
    "BOSS": 2,
    "MINIBOSS": 3,
    "TREASURE": 4
};
var logLevel = 5;
function s() {
    return g_Minigame.m_CurrentScene;
}
function advLog(msg, lvl) {
    if (lvl <= logLevel) {
        console.log(msg);
    }
}
// TEST code
function autoRefreshPage(autoRefreshMinutes) {
     refreshTimer = setTimeout(function() {
        autoRefreshHandler();
     }, autoRefreshMinutes \* 1000 \* 60);
}
function autoRefreshHandler() {
     var enemyData = s().GetEnemy(s().m_rgPlayerData.current_lane, s().m_rgPlayerData.target).m_data; 
     if(typeof enemyData !== "undefined"){
        var enemyType = enemyData.type;
        if(enemyType != ENEMY_TYPE.BOSS) {
            advLog('Refreshing, not boss', 5);
            // !! w.location.reload(true);
            setTimeout(autoRefreshHandler, 1000);
        }else {
            advLog('Not refreshing, A boss!', 5);
            setTimeout(autoRefreshHandler, 3000);
        }
    }else{
        //Wait until it is defined
        advLog('Not refreshing, undefined...', 5);
        setTimeout(autoRefreshHandler, 1000);
    }
}
autoRefreshPage(0.05);

It worked as expected. Only got boss notices on the boss, and undefined/refreshing notices otherwise.

**Comment by ozerugae** [comment]
whoopsie!

**Comment by wchill** [comment]
Still looking for verification that this works with GM/TM and such, as I don't use either

**Comment by Septarius** [comment]
Platform: Chrome x64 Tampermonkey.

I modified the autoRefreshMinutes so that I could force it to refresh more often, testing the collision. http://imgur.com/DF4KppR results look to be be expected. 

Though with how fast bosses seem to go down it might be good to add a current level check % 9  along with the current check because I think you might refresh more often right before a boss level and miss it during the reload then actually refreshing during it. That might be better suited as a separate issue though.

**Comment by wchill** [comment]
Merged in #161.

**Pull request closed without merging**
