### PR TITLE
Footer covering info box fix

### PR DESCRIPTION
**Pull request by ozerugae**
Basically add it before the footer_spacer div / after the game_options div. Not inside the game_options div
https://github.com/wchill/steamSummerMinigame/pull/155

### CODE REVIEW

**Comment by wchill** [comment]
This becomes problematic because of one of the latest commits (actually just before version bump)

https://github.com/oedw/steamSummerMinigame/blob/patch-4/autoPlay.user.js#L298

(see this image http://i.imgur.com/NyprPYo.png)

Also, it does not remove the leave_game_helper yellow box.

**Comment by ozerugae** [comment]
capture

I can try to remove the helper box

**Comment by wchill** [comment]
That's good.

For removing the helper box, just do this

```
var leave_game_box = document.querySelector(".leave_game_helper");
leave_game_box.parentElement.removeChild(leave_game_box);
```

**Comment by ozerugae** [comment]
Thanks for the code, check it out how it looks https://github.com/wchill/steamSummerMinigame/blob/79a2fca34995192f60507a86475192e0642a633e/autoPlay.user.js

**Comment by ozerugae** [comment]
capture

**Comment by wchill** [comment]
Nice, merging.

**Pull request merged**
