### PR TITLE
Add auto-buy

### LINKED ISSUE #123: [Suggestion] Auto-upgrade
I don't think the script currently does this. Should it? I'm tempted to say yes, especially if there is a way to turn it off. Is anyone working on it currently? I'm tempted to start working on it myself, but it's almost midnight and I have work in the morning.

### PR DESCRIPTION
**Pull request by OverlordQ**
Would close #123

### CODE REVIEW

**Comment by ewright352** [comment]
Looked over this a little. Noticed a few things that looked like they might need fixing before this is merged.

1) var critRate = s().m_rgPlayerTechTree.crit_percentage - s().m_rgTuningData.player.crit_percentage;

Here, you're defining the crit rate by subtracting the original 10% from the actual crit rate. That doesn't seem right, unless you know something the rest of us don't.

You're also allowing the crit rate value you use in calculations to be greater than 1, while it doesn't appear that the server calculates extra crits for being over 100%.

I would use this:
var critRate = s().m_rgPlayerTechTree.crit_percentage>1?1:s().m_rgPlayerTechTree.crit_percentage;

But I've also seen people use this:
var critRate = Math.min(s().m_rgPlayerTechTree.crit_percentage,1);

2) Click and DPS element damage

You should consider average element damage in the calculations for Click and DPS or you can't properly compare the values of those upgrades against Lucky Shot.

3) Element upgrade code is missing

4) Lucky Shot upgrade value should be divided by 10

Not sure how to explain this one clearly. In the Click and DPS code, you're using the upgrade multiplier to calculate the value of the upgrade, but multiplier is not the same as damage. Each Click and DPS skill has a multiplier along with a separate base damage of 10. Armor Piercing Round has a multiplier of 1, so the total damage per level is 10. Explosive Rounds has a multiplier of 10, so the total damage per level is 100. Basically, actual damage is 10 times more than multiplier.

But in the Lucky Shot upgrade value calculation, you're using the damage per click value, which is a sum of the actual damage of every upgrade. Because that's actual damage and not a sum of the multipliers, you end up with a value that's 10 times more than it should be.

5) critRate \* critMultiplier + 1

I don't understand why you're adding 1 before multiplying this against everything else. Might be correct. I dunno. Just having trouble making sense of that part of the math in my head.

**Comment by OverlordQ** [comment]
I'll double check when I get home, it was mostly pieced from other code.

**Comment by russeli** [comment]
I've commited fixes based on the feedback so you can piece it together again. :D I still haven't implemented elemental damage upgrades though.  
Also thing to note that this will struggle in the very beginning of the game because it skips locked upgrades rather than calculating cost to buy let's say railgun when explosive rounds is on level 9(lvl 10 ER + lvl 1 Rg).

**Comment by ewright352** [comment]
Important thing: I've just learned that apparently elemental damage doesn't apply when you crit after all. Maybe that makes elemental useless, so upgrading that doesn't matter.

**Comment by russeli** [comment]
Yeah, that's why I've been holding it, not sure how it should be implemented. For users who use only autoattacks elemental upgrades are more apparent, because I believe they don't crit, and so should be eventually implemented in way or another.

**Comment by wchill** [comment]
If we could figure out a way to parameterize the autobuyer so that I can control its behavior using JSON, then we can always change it easily later.

**Pull request closed without merging**
